name: arduino-uno
keyword_file: arduino-uno-keywords.csv

negative_exact_keywords:
  - kit
  - nano
  - mega
  - pro
  - lilypad
  - esp8266
  - esp32
  - stm32
  - attiny85
  - sim900
  - sim808
  - d1
  - digispark
  - yun
  - due
  - sensor
  - kickstarter
  - shield
  - pic
  - raspberry
  - pi
  - wifi
  - cortex
  - lcd
  - tft
  - motor
  - atmega8


negative_any_keywords:
  - sim
