name: arduino-uno
keyword_file: arduino-uno-keywords.csv

negative_exact_keywords:
  - kit
  - nano
  - mega
  - pro
  - lilypad
  - esp8266
  - esp32
  - stm32
  - attiny85
  - sim900
  - sim808
  - d1
  - digispark
  - yun
  - due
  - leonardo
  - sensor
  - kickstarter
  - shield
  - pic
  - raspberry
  - pi
  - wifi
  - cortex
  - lcd
  - tft
  - motor
  - atmega2560
  - attiny13
  - attiny2313
  - attiny24
  - attiny25
  - attiny45
  - attiny84
  - attiny85
  - duemilanove
  - ethernet
  - fio
  - leonardo
  - m0
  - mkr1000
  - zero
  - uno32
  - esplora


negative_any_keywords:
  - sim
